local M = {
  "nvim-treesitter/nvim-treesitter",
  enabled = not vim.g.bigfile_mode and not vim.g.diff_mode,
  lazy = false,
  build = ':TSUpdate'
}

M.config = function()
  require('deponian.treesitter.setup')({
    parsers = {
      'bash',
      'c',
      'cpp',
      'css',
      'diff',
      'git_config',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'gotmpl',
      'gpg',
      'graphql',
      'hcl',
      'helm',
      'html',
      'ini',
      'java',
      'javascript',
      'jq',
      'json',
      'lua',
      'make',
      'markdown',
      'markdown_inline',
      'nginx',
      'passwd',
      'perl',
      'php',
      'python',
      'query',
      'ruby',
      'rust',
      'sql',
      'ssh_config',
      'strace',
      'tcl',
      'terraform',
      'tmux',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
      'zsh',
    },
  })
end

return M
