#!/usr/bin/env bash
# Auto-generated by CMake - DO NOT EDIT MANUALLY
# This script allows building without CMake installed

set -e
cd "$(dirname "$0")/libvscode-diff"

# Detect platform for library extension
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="Darwin"
    LIB_EXT="dylib"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="Linux"
    LIB_EXT="so"
else
    PLATFORM="Unknown"
    LIB_EXT="so"
fi

# Auto-detect compiler (respect CC environment variable)
if [ -z "$CC" ]; then
    if command -v cc >/dev/null 2>&1; then
        CC="cc"
    elif command -v gcc >/dev/null 2>&1; then
        CC="gcc"
    elif command -v clang >/dev/null 2>&1; then
        CC="clang"
    else
        echo "Error: No C compiler found (tried: cc, gcc, clang)"
        exit 1
    fi
fi

echo "Building vscode_diff (standalone mode)..."
echo "Compiler: $CC"
echo "Platform: $PLATFORM"

# Compiler flags
CFLAGS="-Wall -Wextra -std=c11 -O2 -DNDEBUG -DUTF8PROC_STATIC -D_POSIX_C_SOURCE=199309L -Iinclude -Ibuild/include -Ivendor -fPIC"
LDFLAGS="-shared"

# Add -lm for math library on Unix
if [[ "$PLATFORM" != "Darwin" ]]; then
    LDFLAGS="$LDFLAGS -lm"
fi

# Detect OpenMP support
USE_OPENMP=0
if [[ "$PLATFORM" == "Darwin" ]]; then
    # macOS: Check for Homebrew libomp
    if command -v brew >/dev/null 2>&1; then
        LIBOMP_PREFIX=$(brew --prefix libomp 2>/dev/null || true)
        if [ -n "$LIBOMP_PREFIX" ] && [ -f "$LIBOMP_PREFIX/lib/libomp.dylib" ]; then
            USE_OPENMP=1
            CFLAGS="$CFLAGS -Xpreprocessor -fopenmp -I$LIBOMP_PREFIX/include -DUSE_OPENMP"
            LDFLAGS="$LDFLAGS -L$LIBOMP_PREFIX/lib -lomp"
            echo "OpenMP: enabled (Homebrew libomp)"
        fi
    fi
else
    # Linux: Check if compiler supports OpenMP
    echo "int main() { return 0; }" > /tmp/omp_test.c
    if $CC -fopenmp /tmp/omp_test.c -o /tmp/omp_test 2>/dev/null; then
        USE_OPENMP=1
        CFLAGS="$CFLAGS -fopenmp -DUSE_OPENMP"
        LDFLAGS="$LDFLAGS -fopenmp"
        echo "OpenMP: enabled"
    fi
    rm -f /tmp/omp_test.c /tmp/omp_test
fi

if [ "$USE_OPENMP" -eq 0 ]; then
    echo "OpenMP: disabled (not found)"
fi

# Source files (including bundled utf8proc)
SOURCES="\
default_lines_diff_computer.c \
src/char_level.c \
src/line_level.c \
src/myers.c \
src/optimize.c \
src/sequence.c \
src/range_mapping.c \
src/string_hash_map.c \
src/utils.c \
src/print_utils.c \
src/utf8_utils.c \
src/compute_moved_lines.c \
vendor/utf8proc.c"

# Build
mkdir -p build
mkdir -p build/include

# Generate version.h
VERSION=$(cat ../VERSION | tr -d '[:space:]')
sed "s/@''PROJECT_VERSION@/$VERSION/g" include/version.h.in > build/include/version.h

echo "Compiling..."
$CC $CFLAGS $LDFLAGS -o libvscode_diff.$LIB_EXT $SOURCES

echo "Installing to plugin root..."
cp libvscode_diff.$LIB_EXT ../libvscode_diff.$LIB_EXT

echo "✓ Build successful: libvscode_diff.$LIB_EXT"
cd ..
