# https://github.com/mikavilpas/blink-ripgrep.nvim/assets/ URLs time out
# https://github.com/mikavilpas/blink-ripgrep.nvim/compare/ URLs aren't valid until a release is published
exclude = [
  "https://github.com/mikavilpas/blink-ripgrep.nvim/assets/.*",
  "https://github.com/mikavilpas/blink-ripgrep.nvim/compare/\\w+",
]
